# -*- coding: utf-8 -*-
"""arcade

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kJOZcYcXgi2l8RhhfB8AL2ZopwCMMdWx
"""

# player welcome to the arcade
# choose game 1 for rps 2 for guess number
# when pressing q --> it'll take you back to the arcade menu
# again 1 for rps
# 2 for guess my number
# or press x to exit the game
from re import T
import sys
import rps
import guess_number
# import argparse as ag


def play_game(name="PlayerOne"):
    welcome_back = False

    while True:
        if welcome_back == True:
            print(f"\n{name}, welcome back to the Arcade menu.")
        playerchoice = input(
            "\nPlease choose a game:\n1 = Rock Paper Scissors\n2 = Guess My Number \n\nOr press \"x\" to exit the Arcade\n\n")

        if playerchoice not in ["1", "2", "x"]:
            print(f"\n{name}, please enter 1, 2, or x.")
            return play_game(name)

        welcome_back = True

        if playerchoice == "1":
            rock_paper_scissors = rps.rps(name)
            rock_paper_scissors()
        elif playerchoice == "2":
            guess_my_number = guess_number.guess_num(name)
            guess_my_number()
        else:
            print("\nSee you next time!\n")
            sys.exit(f"Bye, {name}!")


if __name__ == '__main__':
    import argparse as ag
    #  import msilib

    parser = ag.ArgumentParser(
        description="Provides a personalized Game Experience."
    )

    parser.add_argument(
        "-n", "--name", metavar="name",
        required=True, help="The name of the person playing the game."
    )
    args = parser.parse_args()

    arcade = play_game(args.name)
    arcade()